/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CLAVES_RPC_H_RPCGEN
#define _CLAVES_RPC_H_RPCGEN

#include <rpc/rpc.h>

#include <pthread.h>

#ifdef __cplusplus
extern "C" {
#endif


struct Coord {
	int x;
	int y;
};
typedef struct Coord Coord;

struct ret_get_value {
	int status;
	char *value1;
	int N_value2;
	struct {
		u_int V_value2_len;
		double *V_value2_val;
	} V_value2;
	struct Coord value3;
};
typedef struct ret_get_value ret_get_value;

struct arg_set_value {
	int key;
	char *value1;
	int N_value2;
	struct {
		u_int V_value2_len;
		double *V_value2_val;
	} V_value2;
	struct Coord value3;
};
typedef struct arg_set_value arg_set_value;

#define CLAVES_PROG 0x31234567
#define CLAVES_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define remote_destroy 1
extern  enum clnt_stat remote_destroy_1(void *, int *, CLIENT *);
extern  bool_t remote_destroy_1_svc(void *, int *, struct svc_req *);
#define remote_set_value 2
extern  enum clnt_stat remote_set_value_1(arg_set_value *, int *, CLIENT *);
extern  bool_t remote_set_value_1_svc(arg_set_value *, int *, struct svc_req *);
#define remote_get_value 3
extern  enum clnt_stat remote_get_value_1(int *, ret_get_value *, CLIENT *);
extern  bool_t remote_get_value_1_svc(int *, ret_get_value *, struct svc_req *);
#define remote_modify_value 4
extern  enum clnt_stat remote_modify_value_1(arg_set_value *, int *, CLIENT *);
extern  bool_t remote_modify_value_1_svc(arg_set_value *, int *, struct svc_req *);
#define remote_delete_key 5
extern  enum clnt_stat remote_delete_key_1(int *, int *, CLIENT *);
extern  bool_t remote_delete_key_1_svc(int *, int *, struct svc_req *);
#define remote_exist 6
extern  enum clnt_stat remote_exist_1(int *, int *, CLIENT *);
extern  bool_t remote_exist_1_svc(int *, int *, struct svc_req *);
extern int claves_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define remote_destroy 1
extern  enum clnt_stat remote_destroy_1();
extern  bool_t remote_destroy_1_svc();
#define remote_set_value 2
extern  enum clnt_stat remote_set_value_1();
extern  bool_t remote_set_value_1_svc();
#define remote_get_value 3
extern  enum clnt_stat remote_get_value_1();
extern  bool_t remote_get_value_1_svc();
#define remote_modify_value 4
extern  enum clnt_stat remote_modify_value_1();
extern  bool_t remote_modify_value_1_svc();
#define remote_delete_key 5
extern  enum clnt_stat remote_delete_key_1();
extern  bool_t remote_delete_key_1_svc();
#define remote_exist 6
extern  enum clnt_stat remote_exist_1();
extern  bool_t remote_exist_1_svc();
extern int claves_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_Coord (XDR *, Coord*);
extern  bool_t xdr_ret_get_value (XDR *, ret_get_value*);
extern  bool_t xdr_arg_set_value (XDR *, arg_set_value*);

#else /* K&R C */
extern bool_t xdr_Coord ();
extern bool_t xdr_ret_get_value ();
extern bool_t xdr_arg_set_value ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CLAVES_RPC_H_RPCGEN */
