/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "claves_rpc.h"
#include "claves.h"
bool_t
remote_destroy_1_svc(int *result, struct svc_req *rqstp)
{
    *result = destroy();
    return TRUE;
}

bool_t
remote_set_value_1_svc(arg_set_value arg1, int *result,  struct svc_req *rqstp)
{
    *result = set_value(arg1.key, arg1.value1, arg1.N_value2, arg1.V_value2.V_value2_val, arg1.value3);
    return TRUE;
}

bool_t
remote_get_value_1_svc(int arg1, ret_get_value *result,  struct svc_req *rqstp)
{
    char *value1 = malloc(MAX_STRING * sizeof(char));
    double *value2 = malloc(MAX_VECTOR * sizeof(double));

    if (!value1 || !value2) {
        if (value1) free(value1);
        if (value2) free(value2);
        result->status = -1;
        return TRUE;
    }

    result->value1 = value1;
    result->V_value2.V_value2_val = value2;

    result->status = get_value(arg1, value1, &result->N_value2, value2, &result->value3);
    result->V_value2.V_value2_len = result->N_value2;

    return TRUE;
}

bool_t
remote_modify_value_1_svc(arg_set_value arg1, int *result,  struct svc_req *rqstp)
{
    *result = modify_value(arg1.key, arg1.value1, arg1.N_value2, arg1.V_value2.V_value2_val, arg1.value3);
    return TRUE;
}

bool_t
remote_delete_key_1_svc(int arg1, int *result,  struct svc_req *rqstp)
{
    *result = delete_key(arg1);
    return TRUE;
}

bool_t
remote_exist_1_svc(int arg1, int *result,  struct svc_req *rqstp)
{
    *result = exist(arg1);
    return TRUE;
}

int
claves_prog_1_freeresult (SVCXPRT *transp, xdrproc_t xdr_result, caddr_t result)
{
    if (xdr_result == (xdrproc_t)xdr_ret_get_value) {
        ret_get_value *res = (ret_get_value *) result;
        if (res->value1) free(res->value1);
        if (res->V_value2.V_value2_val) free(res->V_value2.V_value2_val);
    }

    return 1;
}
