/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "claves_rpc.h"


void
claves_prog_1(char *host)
{
	CLIENT *clnt;
	enum clnt_stat retval_1;
	int result_1;
	enum clnt_stat retval_2;
	int result_2;
	arg_set_value remote_set_value_1_arg1;
	enum clnt_stat retval_3;
	ret_get_value result_3;
	int remote_get_value_1_arg1;
	enum clnt_stat retval_4;
	int result_4;
	arg_set_value remote_modify_value_1_arg1;
	enum clnt_stat retval_5;
	int result_5;
	int remote_delete_key_1_arg1;
	enum clnt_stat retval_6;
	int result_6;
	int remote_exist_1_arg1;

#ifndef	DEBUG
	clnt = clnt_create (host, CLAVES_PROG, CLAVES_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	retval_1 = remote_destroy_1(&result_1, clnt);
	if (retval_1 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_2 = remote_set_value_1(remote_set_value_1_arg1, &result_2, clnt);
	if (retval_2 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_3 = remote_get_value_1(remote_get_value_1_arg1, &result_3, clnt);
	if (retval_3 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_4 = remote_modify_value_1(remote_modify_value_1_arg1, &result_4, clnt);
	if (retval_4 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_5 = remote_delete_key_1(remote_delete_key_1_arg1, &result_5, clnt);
	if (retval_5 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_6 = remote_exist_1(remote_exist_1_arg1, &result_6, clnt);
	if (retval_6 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	claves_prog_1 (host);
exit (0);
}
